#+TITLE: Planetary-nebulae-mc
* Halpha emission of PNe in MC
:PROPERTIES:
:ID:       
:END:

* Motivation: 

* Paper related:
  - 

  

+ Abstract for FoF and meeting in Chile:


    S-PLUS: An atlas of integrated Halpha fluxes for planetary nebulae in the Magellanic Clouds

    We present an atlas of integrated Halpha fluxes for planetary nebulae of the Magellanic Clouds (MC PNe)
    with measurements from the Southern Photometric Local Universe Survey (S-PLUS), a 12 band (7 narrow and
    5 broad) imaging survey that allows us to perform an spatial analysis of the Halpha emission.
    Aperture photometry on the continuum-subtracted images was performed to extract Halpha + [N II] fluxes of
    the MC PNe observed by S-PLUS.  The dust attenuation and [N II] contribution was corrected with empirical relations.
    Amongst its many applications, it can provide baseline data for photoionization and hydrodynamical modelling,
    and allow better estimates of Zanstra temperatures for PN central stars with accurate optical photometry.
    The weak nebular emission of the PNe were also analyzed to investigate the structure of the MC PNe further,
    for which the Halpha surface brightness was estimated. The densities in the nebulae of the PNe were also
    measured using the previously estimated surface brightness.
    These results were compared with previous measurements from the literature. The preliminary results of this study are present in this contribution.


