#+TITLE: Planetary-nebulae-mc
* Halpha emission of PNe in MC
:PROPERTIES:
:ID:       
:END:

* Motivation: 

** Papers related:

   This is a [[https://ui.adsabs.harvard.edu/abs/2006ApJS..167..201S/abstract][paper]] about HST imgaes of PN in the MC.

*** SMC
  - [[https://ui.adsabs.harvard.edu/abs/2015MNRAS.452.1402D/abstract][Drašković, D. et. al 2015]] paper in which are reported four new Planetary Nebula.
    Are in the [[Four-PNe-SMC-2015.csv][table]].
  - A [[https://ui.adsabs.harvard.edu/abs/2014A%26A...561A...8H/abstract][Paper]] about a search for central star in SMC PNe. The [[Tab_2_J_A+A_561_A8_table1.csv][table]] with the PNe.
  - A [[https://ui.adsabs.harvard.edu/abs/2002AJ....123..269J/abstract][paper]] about A Survey for Very Faint Planetary Nebulae in the SMC. Here the [[TAP_1_J_AJ_123_269_table.csv][table]].
  - A [[TAP_3_J_A+A_456_451_PNe_onlySMC][table]] with only the PN SMC from a catalog of both large and small [[TAP_3_J_A+A_456_451_PNe.csv][MC]].
  - An old [[https://ui.adsabs.harvard.edu/abs/2000MNRAS.311..741M/abstract][paper]] about emission line objects in SMC. [[TAP_1_J_MNRAS_311_741_table1.csv][table]].
  - Now, I got the PSF photometry of 74 PNe from the 96 PNe. The table with the SPLUS photometry is [[smc-final-withsplus-mag.csv][here]].

**** PN observed by HST

  - SMC-SMP 2 8.16179 -71.69986
  - SMC-SMP 3 8.59137 -73.22264
  - SMC-SMP 15 12.78071 -73.96047
  - SMC-SMP 16 12.86312 -72.43658
  - SMC-SMP 28 21.04921 -74.04239

*** LMC
  - [[https://ui.adsabs.harvard.edu/abs/2014MNRAS.438.2642R/abstract][Paper]] about PNe in LMC. The data with the PNe are in the [[Tab_7_J_MNRAS_438_2642_table1.csv][table]].
  - Old [[https://ui.adsabs.harvard.edu/abs/2006MNRAS.373..521R/abstract][paper]] about catalog of PNe. Include two tables [[TAP_1_JMNRAS_373_521_table6_LMC_knownPN.csv][one]] with the known PN and [[TAP_1_JMNRAS_373_521_table7_LMC_newPN.csv][other]] with
    new ones.
  - This [[https://ui.adsabs.harvard.edu/abs/2002ApJ...575..178S/abstract][paper]] shows a study of PN in LMC.

recent catlog of PNe:

J/MNRAS/438/2642    LMC PNe multiwavelength photometry       (Reid, 2014)
================================================================================
A multiwavelength analysis of planetary nebulae in the Large Magellanic Cloud.
    Reid W.A.
   <Mon. Not. R. Astron. Soc., 438, 2642-2663 (2014)>
   =2014MNRAS.438.2642R    (SIMBAD/NED BibCode)
================================================================================
ADC_Keywords: Magellanic Clouds ; Planetary nebulae ; Photometry, UBVRI ;
              Photometry, infrared
Keywords: surveys - stars: evolution - planetary nebulae: general -
          galaxies: luminosity function, mass function - Magellanic Clouds
          infrared: general

Abstract:
    This paper examines, compares and plots optical, near- and
    mid-infrared (MIR) photometric data for 605 planetary nebulae (PNe) in
    the Large Magellanic Cloud (LMC). With the aid of multiwavelength
    surveys such as the Spitzer legacy programme Surveying the
    Agents of a Galaxy's Evolution, the Two Micron All Sky Survey and the
    Magellanic Cloud Photometric Survey, plots have been constructed to
    expose the relative contributions from molecular hydrogen, polycyclic
    aromatic hydrocarbons, forbidden emission lines, warm dust continuum
    and stellar emission at various bands. Besides identifying trends,
    these plots have helped to reveal PN mimics including six previously
    known PNe in the outer LMC which are re-classified as other object
    types. Together with continuing follow-up optical observations, the
    data have enabled a substantial reduction in the number of PNe
    previously tagged as 'likely' and 'possible'. The total number of LMC
    PNe is adjusted to 715 but with a greater degree of confidence in
    regard to classification. In each colour-colour plot, the more highly
    evolved LMC PNe are highlighted for comparison with younger, brighter
    PNe. The faintest and most evolved PNe typically cluster in areas of
    colour-colour space occupied by ordinary stars. Possible reasons for
    the wide disparity in infrared colour-colour ratios, such as evolution
    and dust composition, are presented for evaluation. A correlation is
    found between the optical luminosity of PNe, emission-line ratios and
    the MIR dust luminosity at various bands. Luminosity functions using
    the four Infrared Array Camera and Multiband Imaging Photometer of
    Spitzer (MIPS) [24] bands are directly compared, revealing an
    increasing accumulation of PNe within the brightest two magnitudes at
    longer wavelengths. A correlation is also found between the MIPS [24]
    band and the [OIII] 5007 and H{beta} fluxes.

Description:
    Using the 2MASS 6x catalogue for the LMC (Cutri et al. 2003, Cat. II/246;
    2012, Cat. VII/233), magnitudes were obtained for 274 PNe in J, 269 in
    H and 263 in Ks.

    To increase the number of detections available for comparison,
    magnitudes were also obtained from the InfraRed Survey Facility (IRSF)
    Magellanic Clouds Point Source Catalogue (Kato et al., 2007, Cat. II/288).

    The 3.6, 4.5, 5.8 and 8um bands were obtained with the IRAC on board
    Spitzer. This study used the archival data from the Spitzer legacy
    programme SAGE (Meixner et al., 2006, Cat. J/AJ/132/2268) which mapped
    the central 7x7deg^2^ area of the LMC.

    The MIPS data were also obtained from both the Hora et al. (2008, Cat.
    J/AJ/135/726) and Gruendl & Chu (2009, Cat. J/ApJS/184/172) studies.

File Summary:
--------------------------------------------------------------------------------
 FileName      Lrecl  Records   Explanations
--------------------------------------------------------------------------------
ReadMe            80        .   This file
table1.dat       172      605   Magnitude data for each LMC PNe
table2.dat       165       76  *A list of RP objects originally published as
                                 possible PNe 
table3.dat       235       28  *The same as for Table 2 but for RP objects
                                 originally given a probability of 'likely'
                                 and 'true' 
--------------------------------------------------------------------------------
Note on table2.dat: which have now been re-classified or had their status 
  changed following new high-resolution, higher S/N spectral observations 
  and multiwavelength analysis.
Note on table3.dat: which have now been re-classified or had their status 
  as PNe changed following new high-resolution, higher S/N spectral 
  observations and multiwavelength analysis.
--------------------------------------------------------------------------------

See also:
    II/246        : 2MASS All-Sky Catalog of Point Sources (Cutri+ 2003)
    II/288        : IRSF Magellanic Clouds Point Source Catalog (Kato+ 2007)
   VII/233        : The 2MASS Extended sources (IPAC/UMass, 2003-2006)
   J/AJ/128/1606  : Magellanic Clouds Photometric Survey: LMC (Zaritsky+, 2004)
   J/AJ/132/2268  : SAGE calibration stars (Meixner+, 2006)
   J/AJ/135/726   : Spitzer SAGE observations of LMC PNe (Hora+, 2008)
   J/ApJS/184/172 : High- and intermediate-mass YSOs in the LMC (Gruendl+, 2009)
   J/A+A/531/A157 : LMC planetary nebulae (VMC Survey II) (Miszalski+, 2011)

Byte-by-byte Description of file: table1.dat
--------------------------------------------------------------------------------
   Bytes Format Units   Label     Explanations
--------------------------------------------------------------------------------
   1- 12  A12   ---     Name      LMC PNe common name
  14- 19  F6.3  mag     Umag      ?=- MPCS survey U magnitude
  21- 25  F5.3  mag   e_Umag      ? rms uncertainty on Umag
  27- 32  F6.3  mag     Bmag      ?=- MPCS survey B magnitude
  34- 38  F5.3  mag   e_Bmag      ? rms uncertainty on Bmag
      39  A1    ---   n_Bmag      [c] Note on Bmag
  40- 45  F6.3  mag     Vmag      ?=- MPCS survey V magnitude
  47- 51  F5.3  mag   e_Vmag      ? rms uncertainty on Vmag
  53- 58  F6.3  mag     Imag      ?=- MPCS survey I magnitude
  60- 64  F5.3  mag   e_Imag      ? rms uncertainty on Imag
  66- 71  F6.3  mag     Jmag      ?=- IRSF J magnitude
  73- 77  F5.3  mag   e_Jmag      ? rms uncertainty on Jmag
  78- 79  A2    ---   n_Jmag      [?*d ] Note on Jmag (1)
  81- 86  F6.3  mag     Hmag      ?=- IRSF H magnitude
  88- 92  F5.3  mag   e_Hmag      ? rms uncertainty on Hmag
      93  A1    ---   n_Hmag      [?] Note on Hmag
  94- 99  F6.3  mag     Kmag      ?=- IRSF K magnitude
 101-105  F5.3  mag   e_Kmag      ? rms uncertainty on Kmag
     106  A1    ---   n_Kmag      [?*d] Note on Kmag (1)
 108-113  F6.3  mag     [3.6]     ?=- IRAC 3.6um magnitude
 115-119  F5.3  mag   e_[3.6]     ? rms uncertainty on [3.6]
     120  A1    ---   n_[3.6]     [cd] Note on [3.6] (1)
 121-126  F6.3  mag     [4.5]     ?=- IRAC 4.5um  magnitude
 128-132  F5.3  mag   e_[4.5]     ? rms uncertainty on [4.5]
     133  A1    ---   n_[4.5]     [cd] Note on [4.5] (1)
 134-139  F6.3  mag     [5.8]     ?=- IRAC 5.8um magnitude
 141-145  F5.3  mag   e_[5.8]     ? rms uncertainty on [5.8]
     146  A1    ---   n_[5.8]     [d] Note on [5.8] (1)
 147-152  F6.3  mag     [8.0]     ?=- IRAC 8um magnitude
 154-158  F5.3  mag   e_[8.0]     ? rms uncertainty on [8.0]
     159  A1    ---   n_[8.0]     [cd] Note on [8.0] (1)
 160-165  F6.3  mag     [24]      ?=- MPIS 24um magnitude
 167-171  F5.3  mag   e_[24]      ? rms uncertainty on [24]
     172  A1    ---   n_[24]      [cd] Note on [24] (1)
--------------------------------------------------------------------------------
Note (1): Notes as follows:
    c = magnitude for a point source taken from the SAGE catalogue
    d = magnitude taken from Miszalski et al (2011, Cat. J/A+A/531/A157)
    ? = uncertainty flag
    * = 2MASS magnitude
--------------------------------------------------------------------------------

Byte-by-byte Description of file: table2.dat
--------------------------------------------------------------------------------
   Bytes Format Units   Label     Explanations
--------------------------------------------------------------------------------
   1-  4  I4    ---     RP        RP number, [RP2006] NNNN in Simbad
   6-  7  I2    h       RAh       Right ascesnion (J2000)
   9- 10  I2    min     RAm       Right ascesnion (J2000)
  12- 16  F5.2  s       RAs       Right ascesnion (J2000)
      18  A1    ---     DE-       Declination sign (J2000)
  19- 20  I2    deg     DEd       Declination (J2000)
  22- 23  I2    arcmin  DEm       Declination (J2000)
  25- 29  F5.2  arcsec  DEs       Declination (J2000)
  31- 40  A10   ---     ClassNew  New classificaiton (G1)
      42  A1    ---     ProbNew   New classification probability (G2)
  44-165  A122  ---     Reason    Reason (G3)
--------------------------------------------------------------------------------

Byte-by-byte Description of file: table3.dat
--------------------------------------------------------------------------------
   Bytes Format Units   Label     Explanations
--------------------------------------------------------------------------------
   1-  4  I4    ---     RP        RP number, [RP2006] NNNN in Simbad
   6-  7  I2    h       RAh       Right ascesnion (J2000)
   9- 10  I2    min     RAm       Right ascesnion (J2000)
  12- 16  F5.2  s       RAs       Right ascesnion (J2000)
      18  A1    ---     DE-       Declination sign (J2000)
  19- 20  I2    deg     DEd       Declination (J2000)
  22- 23  I2    arcmin  DEm       Declination (J2000)
  25- 29  F5.2  arcsec  DEs       Declination (J2000)
      31  A1    ---     Prob2006  2006 classification probability (G2)
  33- 43  A11   ---     ClassNew  New classificaiton (G1)
      45  A1    ---     ProbNew   New classification probability (G2)
  47-235  A189  ---     Reason    Reason (G3)
--------------------------------------------------------------------------------

Global notes:
Note (G1): Classification code as follows:
   ELS  = emission-line star
   ELS* = identification indicates that the object was re-classified as an 
           ELS in Reid & Parker (2012, Cat. J/MNRAS/425/355)
   LTS  = late-type star
   LPV  = long-period variable
   YSO  = young stellar object
   EmO  = emission object
   PN   = planetary nebula
   SNR  = supernova remnant
Note (G2): Classification probability code as follows:
   K = known
   T = true
   L = likely
   P = possible.
Note (G3):
   (1) refers to analysis using a 2.3m telescope optical spectrum,
   (2) refers to analysis using follow-up observations on 2dF,
   'IR' refers to false infrared colours at 3.6 and 4.5um and 5.8 and 8um
         indicating HII regions or hot stars,
   'Radio' strong radio source (>3mJy). Please see the text (Section 5)
            for more details.
--------------------------------------------------------------------------------

History:
    From electronic version of the journal

================================================================================
(End)                                      Patricia Vannier [CDS]    24-Jul-2017

The table is: 

: TAP_3_J_MNRAS_438_2642_table1.csv
     
*** Galaxy
  - [[https://ui.adsabs.harvard.edu/abs/2013MNRAS.431....2F/abstract][Paper]] about integrated Hα fluxes for 1258 Galactic planetary nebulae.
  - [[https://ui.adsabs.harvard.edu/abs/2016MNRAS.455.1459F/abstract][This]] is about the H$alpha$ surface brightness-radius relation:
    a robust statistical distance indicator for planetary nebulae.
  - [[http://202.189.117.101:8999/gpne/dbMainPage.php][HASH]]. This is the most recent catalog of Galactic PNe. 

** Find the coincident between SMC catalogs
:PROPERTIES:
:ID:       LUIS
:END:
#+BEGIN_SRC python 
  import numpy as np
  from astropy.table import Table, Column, MaskedColumn, vstack
  import astropy.coordinates as coord
  
  # arctab = Table.read('luis-programas/arcs-summary-unique.ecsv', 
  #                     format='ascii.ecsv')
  # #                    fill_values=('--', np.nan) ).filled(np.nan)
  # outcols = ['Object']
  
  # arctab['coord'] = coord.SkyCoord(ra=arctab['RA'], dec=arctab['Dec'],
  #                                  unit=('hourangle', 'deg'))
  
  catalogs = {'D': {'file': 'Four-PNe-SMC-2015.csv',
		      'ID': 'ID'},
	      'HGS': {'file': 'Tab_2_J_A+A_561_A8_table1.csv',
		       'ID': 'COUP'},
	      'GM': {'file': 'TAP_1_J_AJ_123_269_table.csv',
		      'ID': 'MAX'},
	      'LSMC': {'file': 'TAP_3_J_A+A_456_451_PNe_onlySMC.csv',
		      'ID': 'recno'},
				   }
  
  tab_base = Table.read('Tab_2_J_A+A_561_A8_table1.ecsv', 
		       format='ascii.ecsv')
  tab_base['coord'] = coord.SkyCoord(ra=tab_base['RAJ2000'], dec=tab_base['DEJ2000'],
				    unit=('deg', 'deg'))
  # tab_four = Table.read('Four-PNe-SMC-2015.ecsv', 
  # 		     format='ascii.ecsv')
  # tab_four['coord'] = coord.SkyCoord(ra=tab_base['RA'], dec=tab_base['DEC'],
  # 				  unit=('hourangle', 'deg'))
  tab_269 = Table.read('TAP_1_J_AJ_123_269_table.ecsv', 
		       format='ascii.ecsv')
  tab_269['coord'] = coord.SkyCoord(ra=tab_269['RAJ2000'], dec=tab_269['DEJ2000'],
				    unit=('deg', 'deg'))
  tab_smc = Table.read('TAP_3_J_A+A_456_451_PNe_onlySMC.ecsv', 
		       format='ascii.ecsv')
  tab_smc['coord'] = coord.SkyCoord(ra=tab_smc['_RA'], dec=tab_smc['_DE'],
				    unit=('deg', 'deg'))
  MAXSEP = 1.0
  # Definition
  def unmatch(tab, tab_base):
      sourceseps = []
      for pn in tab:
	  seps = pn['coord'].separation(tab_base['coord']).arcsec
	  iclosest = seps.argmin()
	  sourceseps.append(seps[iclosest])
      return sourceseps
  
  Col_base = ["Name", "RAJ2000", "DEJ2000"]
  tab_base_ = tab_base[Col_base]
  tab_269.rename_column('recno', 'Name')
  tab_269_ = tab_269[Col_base]
  tab_269_
  tab_269_['Name'] = tab_269_['Name'].astype(str)
  #mask
  mask = np.array(unmatch(tab_269, tab_base)) >= MAXSEP
  tab_269_unmatch = tab_269_[mask]
  
  # New table base + 269
  T12_base = vstack([tab_base_, tab_269_unmatch])
  T12_base['coord'] = coord.SkyCoord(ra=T12_base['RAJ2000'], dec=T12_base['DEJ2000'], unit=('deg', 'deg'))
  
  # Other unmacth
  T12_base_ = T12_base[Col_base]
  tab_smc.rename_column('_RA', 'RAJ2000')
  tab_smc.rename_column('_DE', 'DEJ2000')
  tab_smc_ = tab_smc[Col_base]
  tab_smc_
  
  mask1 = np.array(unmatch(tab_smc, T12_base)) >= MAXSEP
  tab_smc_unmatch = tab_smc_[mask1]
  
  # Final table
  tab_final = vstack([T12_base_, tab_smc_unmatch])
  
  # Save
  tab_final.write("smc-final-2via.ecsv", format="ascii.ecsv", overwrite=True)
  df = tab_final.to_pandas(
  df.to_csv("smc-final-2via.csv", index=False)
  
  
  #+END_SRC

#+RESULTS:

** TODO The final list SMC
   I added two column in the table, one indicates if the objet is in the SPLUS field.
   And other one if the object has spectra.

#+name: splus-status
| Name         | Splus Status | Spectra |
|--------------+--------------+---------|
| LHA 115-N 4  |            0 | n       |
| LHA 115-N 5  |            0 | n       |
| LHA 115-N 6  |            0 |         |
| Jacoby SMC 1 |            0 |         |
| [MA93] 44    |            0 |         |
| LHA 115-N 7  |            0 |         |
| MGPN SMC 6   |            0 |         |
| [JD2002] 1   |            0 |         |
| LIN 66       |            0 |         |
| LIN 71       |            0 |         |
| [JD2002] 2   |            0 |         |
| [JD2002] 5   |            0 |         |
| LHA 115-N 29 |            0 |         |
| [JD2002] 6   |            0 |         |
| Jacoby SMC 9 |            0 |         |
| SMP SMC 12   |            0 |         |
| [JD2002] 7   |            0 |         |
| [M95] 3      |            0 |         |
| LHA 115-N 38 |            0 |         |
| LHA 115-N 40 |            0 |         |
| [MA93] 406   |            0 |         |
| LHA 115-N 43 |            0 |         |
| [JD2002] 12  |            0 |         |
| LHA 115-N 42 |            0 |         |
| LHA 115-N 47 |            0 |         |
| LIN 239      |            0 |         |
| [MA93] 891   |            0 |         |
| LIN 302      |            0 |         |
| LIN 305      |            0 |         |
| [JD2002] 17  |            0 |         |
| LIN 343      |            0 |         |
| LHA 115-N 68 |            0 |         |
| LHA 115-N 70 |            0 |         |
| [JD2002] 19  |            0 |         |
| LIN 357      |            0 |         |
| [JD2002] 20  |            0 |         |
| [JD2002] 23  |            0 |         |
| [MA93] 1438  |            0 |         |
| LIN 430      |            0 |         |
| [MA93] 1709  |            0 |         |
| [MA93] 1714  |            0 |         |
| SMP SMC 34   |            0 |         |
| [MA93] 1762  |            0 |         |
| LHA 115-N 87 |            0 |         |
| LIN 536      |            0 |         |
| 1            |            0 |         |
| 3            |            0 |         |
| 4            |           1? |         |
| 5            |            0 |         |
| 7            |            0 |         |
| 8            |            0 |         |
| 9            |            0 |         |
| 10           |            0 |         |
| 11           |            0 |         |
| 12           |            0 |         |
| 13           |            0 |         |
| 14           |            0 |         |
| 15           |            0 |         |
| 16           |            0 |         |
| 17           |            0 |         |
| 18           |            0 |         |
| 19           |            0 |         |
| 20           |            0 |         |
| 21           |            0 |         |
| 22           |            0 |         |
| 23           |            0 |         |
| 25           |            0 |         |
| 24           |            0 |         |
| SMP_SMC_1    |            0 |         |
| SMP_SMC_2    |            0 |         |
| SMP_SMC_4    |            0 |         |
| SMP_SMC_7    |            0 |         |
| SMP_SMC_9    |            0 |         |
| SMP_SMC_10   |            0 |         |
| SMP_SMC_11   |            0 |         |
| SMP_SMC_17   |            0 |         |
| SMP_SMC_20   |            0 |         |
| SMP_SMC_22   |            0 |         |
| SMP_SMC_32   |            0 | y       |
| MGPN_SMC_1   |            0 |         |
| MGPN_SMC_10  |            0 |         |
| MGPN_SMC_11  |            0 |         |
| MGPN_SMC_12  |            0 | y       |
| MGPN_SMC_13  |           1? |         |
| MGPN_SMC_2   |           1? |         |
| MGPN_SMC_3   |            0 |         |
| MGPN_SMC_5   |            0 |         |
| MGPN_SMC_7   |            0 |         |
| MGPN_SMC_8   |            0 |         |
| [M95]_1      |            1 |         |
| [M95]_2      |            0 |         |
| LHA_115-N_8  |           0? |         |
| DPR1         |            0 | y       |
| DPR2         |            0 | y       |
| DPR3         |            0 | y       |
| DPR4         |            0 | y       |
	     		   		   

#+header: :var table=splus-status
#+BEGIN_SRC python :results output
  from astropy.table import Table
  
  splus, sp = [], []
  for a, b, c in table:
      splus.append(b)
      sp.append(c)
  
  tab = Table.read("smc-final.ecsv", format = "ascii.ecsv")
  tab["SplusStatus"] = splus
  tab["Spectra"] = sp
  
  #Save the tables updates
  #ASCII
  tab.write("smc-final-update.ecsv", format="ascii.ecsv", overwrite=True)
  #PANDAS
  df = tab.to_pandas()
  df.to_csv("smc-final-update.csv", index=False)
  
#+END_SRC

#+RESULTS:

** First results
    
Then, the final [[smc-final-update.csv][table]] is almost done.
Remenber a I have to check whats PN have spectra.

- Amanda found that the table with the PN with SPLUS photometry has duplicate
  objects. So, she made a new [[smc-final-withsplus-mag-updated.csv][one]].

- Amanda created the Halpha maps for some PNe of the small Magellanic Cloud.
  It is possible to access [[preliminary_maps_smc_withsplus_mag][here]].

- I also ran my version of the script to subtract Halpha emission. [[Halpha-emission][Here]] some examples.

- Now, Amanda, applied a filter (?), before to make the subtraction of the filter, [[halpha_imgs_withBWfilter][here]] the Halpha images.

** Abstract for FoF and meeting in Chile:

    S-PLUS: An atlas of integrated Halpha fluxes for planetary nebulae in the Magellanic Clouds

    We present an atlas of integrated Halpha fluxes for planetary nebulae of the Magellanic Clouds (MC PNe)
    with measurements from the Southern Photometric Local Universe Survey (S-PLUS), a 12 band (7 narrow and
    5 broad) imaging survey that allows us to perform an spatial analysis of the Halpha emission.
    Aperture photometry on the continuum-subtracted images was performed to extract Halpha + [N II] fluxes of
    the MC PNe observed by S-PLUS. The dust attenuation and [N II] contribution was corrected with empirical relations.
    Amongst its many applications, it can provide baseline data for photoionization and hydrodynamical modelling,
    and allow better estimates of Zanstra temperatures for PN central stars with accurate optical photometry.
    The weak nebular emission of the PNe were also analyzed to investigate the structure of the MC PNe further,
    for which the Halpha surface brightness was estimated. The densities in the nebulae of the PNe were also
    measured using the previously estimated surface brightness.
    These results were compared with previous measurements from the literature. The preliminary results of
    this study are present in this contribution.

<<<<<<< HEAD
* Extinction correction

For PNe the extinction correction could be done by ratio lines:

 For example, commonly used ratio lines are Hα/Hβ, Hγ/Hβ, or Hδ/Hβ. These lines are sensitive 
to the reddening caused by interstellar dust.

examples of calibration equations commonly used to estimate the color excess (E(B-V)) in planetary nebulae based on ratio line measurements:

    + Hα/Hβ ratio calibration:
    E(B-V) = 2.22 * log10((Hα/Hβ)observed / (Hα/Hβ)intrinsic)

    + Hγ/Hβ ratio calibration:
    E(B-V) = 1.06 * log10((Hγ/Hβ)observed / (Hγ/Hβ)intrinsic)

    + Hδ/Hβ ratio calibration:
    E(B-V) = 0.73 * log10((Hδ/Hβ)observed / (Hδ/Hβ)intrinsic)

These equations illustrate the general form of the calibration equations. However, please note 
that the specific coefficients and ratios used in these equations may vary depending on the calibration 
study and the particular set of ratio lines being employed.

It's important to consult the relevant literature or research papers for 
the specific calibration equations that are appropriate for your study and the ratio lines you have selected. 
These publications often provide detailed information about the calibration methodology, sample selection, 
and uncertainties associated with the calibration.

By applying the appropriate calibration equation to your observed line flux ratios, 
you can estimate the color excess (E(B-V)) for your planetary nebula based on those ratio measurements.

+ A [[https://ui.adsabs.harvard.edu/abs/2013MNRAS.436..604R/abstract][paper]] sobre correction extinctions of LMC. 
+
 
=======
    
>>>>>>> 9340040bfc85c396585b2c042387d33a265fc133
* Products

  Después de medir la emisión de H-alpha de las nebulosas planetarias utilizando fotometría de tres filtros,
  hay varias cosas que puedes hacer con los datos. Algunas sugerencias son:

    - Calcular la temperatura electrónica y la densidad electrónica de la nebulosa: Utilizando los datos
    de fotometría de los tres filtros, puedes calcular la relación de intensidades de emisión de diferentes
    líneas de emisión, como H-alpha y H-beta. Estas relaciones se utilizan para calcular la temperatura
    electrónica de la nebulosa. La intensidad de la línea de emisión H-alpha también se puede utilizar
    para calcular la densidad electrónica de la nebulosa.

    - Analizar la estructura de la nebulosa: La intensidad de la emisión de H-alpha varía en diferentes
    partes de la nebulosa planetaria, lo que puede indicar diferentes estructuras en la nebulosa,
    como chorros o cascarones. Puedes utilizar los datos de fotometría para crear mapas de intensidad
    y analizar la estructura de la nebulosa.

    - Identificar estrellas centrales y determinar sus propiedades: En algunas nebulosas planetarias,
    es posible identificar la estrella central que ioniza la nebulosa.
    Utilizando los datos de fotometría de H-alpha y otros filtros, puedes determinar
    las propiedades de la estrella central, como su temperatura y luminosidad.

    - Comparar las propiedades de la nebulosa con modelos teóricos: Utilizando los
    datos de fotometría y las propiedades calculadas de la nebulosa, puedes
    comparar tus resultados con modelos teóricos de nebulosas planetarias.
    Esto puede ayudar a entender mejor la formación y evolución de estas estructuras.

En resumen, después de medir la emisión de H-alpha de las nebulosas planetarias utilizando
fotometría de tres filtros, hay varias cosas que puedes hacer con los datos, como calcular
la temperatura y densidad electrónica, analizar la estructura de la nebulosa, identificar
estrellas centrales y comparar tus resultados con modelos teóricos.



